name: pi-hole

services:
  pi-hole:
    container_name: pi-hole
    env_file:
      - secrets.enc.env
    image: pihole/pihole:latest@sha256:91dc91ddd413bf461c283204558f8f21839851e9824799075a7ceff7c77eea40
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 8081:80
    restart: unless-stopped
    volumes:
      - pi-hole:/etc/pihole
      - /etc/localtime:/etc/localtime:ro

volumes:
  pi-hole:
    external: true
    name: pi-hole
