name: gotify

networks:
  tunnel:
    external: true
    name: tunnel

services:
  gotify:
    container_name: gotify
    image: gotify/server:latest@sha256:4702c392ca723d5016fc938c8b22572c3509efca812bdc5221d25158ba0201e3
    networks:
      - tunnel
    restart: unless-stopped
    volumes:
      - gotify:/app/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  gotify:
    external: true
    name: gotify
