name: pihole

services:
  pihole:
    container_name: pihole
    env_file:
      - secrets.enc.env
    image: pihole/pihole:latest@latest@sha256:bf6a909c47526000014be90046b367d1cf8fb0c119768455cac60de9948a1de8
    ports:
      - 53:53
      - 8081:8081
    restart: unless-stopped
    volumes:
      - pihole:/etc/pihole
      - /etc/localtime:/etc/localtime:ro

volumes:
  pihole:
    external: true
    name: pihole
