name: home-assistant

services:
  home-assistant:
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable@sha256:3e2dff545c46e91f4ab2b21597016011d76d0de58bc8eaf51d75e841f337bf88
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro

volumes:
  home-assistant:
    external: true
    name: home-assistant
