name: home-assistant

services:
  home-assistant:
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable@sha256:043ab74ba0ad529734d7d77ca3e893f286410864619329d5e8ca0524c3d260c1
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro

volumes:
  home-assistant:
    external: true
    name: home-assistant
