name: homepage

services:
  homepage:
    container_name: homepage
    env_file:
      - secrets.enc.env
    image: ghcr.io/gethomepage/homepage:latest@sha256:7fa7b07a26bd8d90a44bb975c6455b10d8dee467ce674b040750ffb4a0f486d6
    ports:
      - 30001:30001
    restart: unless-stopped
    volumes:
      - homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  homepage:
    external: true
    name: homepage
