name: nginx-proxy-manager

services:
  nginx-proxy-manage:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest@sha256:a047f943b8544502417ad58b33f2468dea0eee46370fbccae3c14522e01fc17c
    network_mode: host
    restart: unless-stopped
    volumes:
      - nginx-proxy-manager:/data
      - nginx-proxy-manager-lets-encrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro

volumes:
  nginx-proxy-manager:
    external: true
    name: nginx-proxy-manager
  nginx-proxy-manager-lets-encrypt:
    external: true
    name: nginx-proxy-manager-lets-encrypt
