name: nginx-proxy-manager

services:
  nginx-proxy-manage:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest@sha256:08e0997ce1cc8738637b0e271a727815ea89ed564ce392e0f9035f1a03c089c5
    network_mode: host
    restart: unless-stopped
    volumes:
      - nginx-proxy-manager:/data
      - nginx-proxy-manager-lets-encrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro

volumes:
  nginx-proxy-manager:
    external: true
    name: nginx-proxy-manager
  nginx-proxy-manager-lets-encrypt:
    external: true
    name: nginx-proxy-manager-lets-encrypt
